# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('standart', 'Standart'), ('stacked', 'Stacked')], default='standart', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='page',
            name='show_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='video_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
