# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_leave_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='jumbtron_bg_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='page',
            name='jumbtron_text_color',
            field=models.CharField(default='#777777', max_length=7),
        ),
    ]
